StudentApp.Web/Controllers/SubjectClassController.cs
using SchoolApp.Data;
using SchoolApp.DataTable.Extension;
using SchoolApp.DataTable.Search;
using SchoolApp.DataTable.Sort;
using SchoolApp.Service.SubjectService;
using SchoolApp.Web.Code.Serialization;
using SchoolApp.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;

using System.Web.Mvc;



namespace SchoolApp.Web.Controllers
{
    public class SubjectClassController : BaseController

    {
        private readonly ISubjectService _subjectmasterService;
        public SubjectClassController(ISubjectService subjectmasertService)
        {
            this._subjectmasterService = subjectmasertService;

        }
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Index(SchoolApp.DataTable.DataTable dataTable)
        {
            List<DataTableRow> table = new List<DataTableRow>();

            List<int> column1 = new List<int>();
            for (int i = dataTable.iDisplayStart; i < dataTable.iDisplayStart + dataTable.iDisplayLength; i++)
            {
                column1.Add(i);
            }

            //This Methods for seraching in dataTable
            var query = new SearchQuery<SubjectMaster>();

            if (!string.IsNullOrEmpty(dataTable.sSearch))
            {
                string sSearch = dataTable.sSearch.ToLower();
                query.AddFilter(q => q.Subject.Contains(sSearch));
            }
            // This Methods for sorting in dataTable
            var sortColumnIndex = Convert.ToInt32(Request["iSortCol_0"]);
            var sortDirection = Request["sSortDir_0"];
            switch (sortColumnIndex)
            {
                case 2:
                    query.AddSortCriteria(new ExpressionSortCriteria<SubjectMaster, string>(q => q.Subject, sortDirection == "asc" ? SortDirection.Ascending : SortDirection.Descending));
                    break;

                case 3:
                    query.AddSortCriteria(new ExpressionSortCriteria<SubjectMaster, bool>(q => q.IsActive, sortDirection == "asc" ? SortDirection.Ascending : SortDirection.Descending));
                    break;
            }
            //for pagination
            query.Take = dataTable.iDisplayLength;
            query.Skip = dataTable.iDisplayStart;

            int count = dataTable.iDisplayStart + 1, total = 0;

            //To get data from table  using searchquery
            IEnumerable<SubjectMaster> subjectmasters = _subjectmasterService.GetSubjectMasterList(query, out total).Entities;

            foreach (SubjectMaster subjectmaster in subjectmasters)
            {


                table.Add(new DataTableRow("rowId" + count.ToString(), "dtrowclass")
                {
                    subjectmaster.SubjectId.ToString(), //0
                    count.ToString(),//1
                    subjectmaster.Subject,//2
                    subjectmaster.IsActive?"Active":"Inactive" //3

                });
                count++;
            }
            return new DataTableResultExt(dataTable, table.Count(), total, table);
        }



        // add edit method
        public PartialViewResult AddEditSubject(int id=0)
        {

            SubjectViewModel model = new SubjectViewModel();
            SubjectMaster subMaster = new SubjectMaster();
           
            if (id>0)
            {
                subMaster = _subjectmasterService.FindById(id);
            }
            model.SubjectId = id > 0 ? id : 0;
            model.Subject = subMaster.Subject;
            model.IsActive = subMaster.IsActive;

            return PartialView("AddEditSubject", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveSubjectMaster(int? id, SubjectViewModel model)

        {

            try
            {
                if (ModelState.IsValid)
                {
                    SubjectMaster subjectMaster = new SubjectMaster();
                    if (model.SubjectId > 0)
                    {
                        subjectMaster = _subjectmasterService.FindById(model.SubjectId);
                     
                    }
                    else
                    {
                      
                    }

                    subjectMaster.Subject = model.Subject?.Trim() ?? "";
                    subjectMaster.IsActive = model.IsActive;
                
                    _subjectmasterService.SaveSubjectMaster(subjectMaster);

                }
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {

                return NewtonSoftJsonResult(new RequestOutcome<string> { Data = ex.GetBaseException().Message, IsSuccess = false });
            }
          
        }

        [HttpGet]
        public PartialViewResult DeleteSubjectMaster()
        {
            return PartialView("_ModalDelete", new Modal
            {
                Size = ModalSize.Small,
                IsHeader = true,
                Message = "Are you sure want to delete this Subject?",
                Header = new ModalHeader { Heading = "Delete Subject" },
                Footer = new ModalFooter { SubmitButtonText = "Yes", CancelButtonText = "No" }
            });
        }

        [HttpPost]
        public ActionResult DeleteSubjectMaster(int id)
        {
            try
            {
                int get = _subjectmasterService.DeleteSubjectMasterPresenter(id);
                if (get == id)
                {
                    ShowSuccessMessage("Success", "Subject is successfully deleted", false);
                    return NewtonSoftJsonResult(new RequestOutcome<string> { Data = "Data Deleted" });
                }
                else
                {
                    return NewtonSoftJsonResult(new RequestOutcome<string> { Data = "Error Occourd" });
                }

            }
            catch (Exception ex)
            {
                return NewtonSoftJsonResult(new RequestOutcome<string> { Data = ex.GetBaseException().Message, IsSuccess = false });
            }

        }

    }
}

StudentApp.Web/Views/SubjectClass/AddEditSubject.cshtml
@model SchoolApp.Web.Models.SubjectViewModel


<div id="adminUpdateLocationModal">

    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header ">
            <button type="button" class="close font16" data-dismiss="modal"><i class="fa fa-times"></i></button>
            Add/Update  ClassMaster
            <h4 class="modal-title"><b><span class="UpdateBrand"></span></b></h4>
        </div>
        <div class="modal-body">
            <div class="full-wdth clearfix otp-section">
                @using (Html.BeginForm("SaveSubjectMaster", "SubjectClass", null, FormMethod.Post, new { @class = "form-horizontal", id = "formAddEditSubjectMaster" }))
                {

                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)

                    <input type="hidden" name="SubjectId" id="ClassId"  value="@Model.SubjectId" />
                    <div id="validation-summary"></div>
                    <div id="adminAddAllergyMessageDiv" class="alert " style="display:none"> </div>
                    <div class="form-group">
                        <div class="col-sm-3 label-schedule">@Html.Label("Subject", "Subject Name", new { @class = "main-label requiredasterisk" })</div>
                        <div class="col-sm-9">
                            @Html.TextBoxFor(model =>model.Subject, null, htmlAttributes: new { @class = "form-control form-control-sm", placeholder = "Enter Class", maxlength = "100" })
                            @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="form-group">
                        @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="checkbox">
                                @Html.CheckBoxFor(model => model.IsActive, new { @class = "form-checkbox" })
                                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                            </div>


                        </div>
                    </div>

                    <div class="modal-footer customMargin">
                        <button data-dismiss="modal" id="btn-cancel" class="btn btn-default" type="button">Cancel</button>
                        <button class="btn btn-primary" id="btn-submit" type="submit">
                            Submit
                        </button>
                    </div>
                }

            </div>
        </div>

    </div>

</div>
<link href="~/Content/css/bootstrap-switch.css" rel="stylesheet" />

StudentApp.Web/Views/SubjectClass/Index.cshtml
@{
    ViewBag.Title = "ClassViewIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section styles{
    <link href="~/Content/css/dataTables.bootstrap4.min.css" rel="stylesheet" />

}

<section class="content-header">
    <h1>
        Manage Subject Master
    </h1>

</section>
<section class="content">

    <div class="row">
        <div class="col-xs-12">
            <div class="box">

                <div class="box-body">
                    <div class="clearfix">
                        <div class="btn-group">
                            <a id="addClassMastermentmodal" data-toggle="modal" href="@Url.Action("AddEditSubject","SubjectClass")" data-target="#modal-add-edit-subjectmaster" class="btn btn-primary">
                                <i class="fa fa-plus"></i> Add New
                            </a>
                        </div>
                    </div>
                </div>
                <div class="box-body table-responsive">

                    <table id="grid-subjectmaster-management" class="table table-bordered table-striped table-condensed">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th width="2%">#</th>
                                <th>Class</th>
                                <th>IsActive</th>
                                <th>Action</th>

                            </tr>
                        </thead>
                        <tbody></tbody>
                        <tfoot></tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

@Html.Partial("_Modal", new Modal { ID = "modal-add-edit-subjectmaster", AreaLabeledId = "modal-add-edit-subjectmaster-label", Size = ModalSize.Large })
@Html.Partial("_Modal", new Modal { ID = "modal-delete-subjectmaster", AreaLabeledId = "modal-delete-subjectmaster-label", Size = ModalSize.Medium })
@section scripts
{

    <script src="~/Scripts/views/subjectmaster/subjectlist.js"></script>
    <link href="~/Content/css/bootstrap-switch.css" rel="stylesheet" />
}