StudentApp.Web/Controllers/FacultyAllocationController.cs
using Newtonsoft.Json;
using SchoolApp.Data;
using SchoolApp.DataTable.Extension;
using SchoolApp.DataTable.Search;
using SchoolApp.DataTable.Sort;
using SchoolApp.Service.ClassMasterServices;
using SchoolApp.Service.FacultyAllocation;
using SchoolApp.Service.FacultyService;
using SchoolApp.Service.SubjectService;
using SchoolApp.Web.Code.Serialization;
using SchoolApp.Web.Model;
using SchoolApp.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchoolApp.Web.Controllers
{
    public class FacultyAllocationController : BaseController
    {
        // GET: FacultyAllocation

        private readonly IFacultyServices facultyServices;
        private readonly ISubjectService subjectService;
        private readonly IClassMasterService classMasterService;
        private readonly IFacultyAllocationServices facultyAllocationservices;

        public FacultyAllocationController(IFacultyServices facultyServices, ISubjectService subjectService, IClassMasterService classMasterService, IFacultyAllocationServices facultyAllocationServices)
        {
            this.facultyServices = facultyServices;
            this.subjectService = subjectService;
            this.classMasterService = classMasterService;
            this.facultyAllocationservices = facultyAllocationServices;

        }
        public ActionResult AllocationIndex()
        {

            return View();
        }


        [HttpPost]
        public ActionResult AllocationIndex(SchoolApp.DataTable.DataTable dataTable)
        {


            List<DataTableRow> table = new List<DataTableRow>();

            List<int> column1 = new List<int>();
            for (int i = dataTable.iDisplayStart; i < dataTable.iDisplayStart + dataTable.iDisplayLength; i++)
            {
                column1.Add(i);
            }

            //This Methods for seraching in dataTable
            var query = new SearchQuery<FacultyClassAllocation>();

            query.IncludeProperties = "ClassMaster,FacultyMaster,SubjectMaster";

            if (!string.IsNullOrEmpty(dataTable.sSearch))
            {
                string sSearch = dataTable.sSearch.ToLower();
                query.AddFilter(q => ((q.FacultyMaster.FirstName)+""+(q.FacultyMaster.LastName)).Contains(sSearch));

            }
            // This Methods for sorting in dataTable
            var sortColumnIndex = Convert.ToInt32(Request["iSortCol_0"]);
            var sortDirection = Request["sSortDir_0"];
            switch (sortColumnIndex)
            {

                case 2:
                    query.AddSortCriteria(new ExpressionSortCriteria<FacultyClassAllocation, string>(q => q.FacultyMaster.FirstName+""+q.FacultyMaster.LastName, sortDirection == "asc" ? SortDirection.Ascending : SortDirection.Descending));
                    break;

                case 3:
                    query.AddSortCriteria(new ExpressionSortCriteria<FacultyClassAllocation, string>(q => q.ClassMaster.Class, sortDirection == "asc" ? SortDirection.Ascending : SortDirection.Descending));
                    break;
                case 4:
                    query.AddSortCriteria(new ExpressionSortCriteria<FacultyClassAllocation, string>(q => q.SubjectMaster.Subject, sortDirection == "asc" ? SortDirection.Ascending : SortDirection.Descending));
                    break;

                default:

                    break;
            }
            //for pagination
            query.Take = dataTable.iDisplayLength;
            query.Skip = dataTable.iDisplayStart;

            int count = dataTable.iDisplayStart + 1, total = 0;

            //To get data from table  using searchquery
            IEnumerable<FacultyClassAllocation> facultyAllocation = facultyAllocationservices.GetFacultyAllocationList(query, out total).Entities;

            foreach (FacultyClassAllocation facultyallo in facultyAllocation)
            {

                table.Add(new DataTableRow("rowId" + count.ToString(), "dtrowclass")
                {

                    facultyallo.FacultyAllocationId.ToString(), //0
                     count.ToString(), //1
                    Convert.ToString(facultyallo.FacultyMaster?.FirstName)+" "+ Convert.ToString(facultyallo.FacultyMaster?.LastName),//2
                    Convert.ToString(facultyallo.ClassMaster?.Class),//3
                     Convert.ToString(facultyallo.SubjectMaster?.Subject),//4
                     Convert.ToString(facultyallo.Class_Start_Time), //5
                     Convert.ToString(facultyallo.Class_End_Time), //6
                    Convert.ToString(facultyallo.IsActive?"Active":"Inactive") //7

                }); 
                count++;
            }
            return new DataTableResultExt(dataTable, table.Count(), total, table);
        }


        // create method for add and edit 

        [HttpGet]
        public PartialViewResult AddUpdateAllocation(int? id)
        {
            FacultyAllocationModel model = new FacultyAllocationModel();

            var facultyList = facultyServices.GetAllFacultyList();
                var subjectList = subjectService.GetAllSubjectList();
                var classList = classMasterService.GetAllClassList();
            //var Starttime=facultyAllocationservices.


                foreach (var faculty in facultyList)
                {
                    model.FacultyList.Add(new SelectListItem
                    {
                        Text = $"{faculty.FirstName} {faculty.LastName}",
                        Value = faculty.FacultyId.ToString()
                    });
                }
                foreach (var subject in subjectList)
                {
                    model.SubjectList.Add(new SelectListItem
                    {
                        Text = subject.Subject,
                        Value = subject.SubjectId.ToString()

                    });
                }
                foreach (var classValue in classList)
                {
                    model.ClassList.Add(new SelectListItem
                    {
                        Text = classValue.Class,
                        Value = classValue.ClassId.ToString()

                    });
                }
            if (id.HasValue)
            {

                if (id != null && id > 0)
                {
                    var facultyAllocations = facultyAllocationservices.FindById(Convert.ToInt32(id));
                    model.FacultyList.Find(a => a.Value == facultyAllocations.FacultyId.ToString()).Selected = true;
                    model.ClassList.Find(a => a.Value == facultyAllocations.ClassId.ToString()).Selected = true;
                    model.SubjectList.Find(a => a.Value == facultyAllocations.SubjectId.ToString()).Selected = true;
                    model.Class_End_Time = facultyAllocations.Class_End_Time;
                    model.Class_Start_Time = facultyAllocations.Class_Start_Time;
                    model.IsActive = facultyAllocations.IsActive;
                    model.FacultyAllocationId = facultyAllocations.FacultyAllocationId;
                }
            }
            return PartialView("AsignClassFaculty", model);
        }


        [HttpPost]
        public ActionResult SaveFacultyAllocation(int? id, FacultyAllocationModel model)
        {

            try
            {

                 if (ModelState.IsValid)
                {
                    bool isExist = id.HasValue;
                    FacultyClassAllocation facultyAllocations = isExist ? facultyAllocationservices.GetFacultyAllocationPresenter(id.Value) : new FacultyClassAllocation();

                   // FacultyClassAllocation facultyAllocations = new FacultyClassAllocation();

                    if (model.FacultyAllocationId > 0)
                    {
                        
                        facultyAllocations = facultyAllocationservices.FindById(Convert.ToInt32(model.FacultyAllocationId));
                        facultyAllocations.FacultyId = model.FacultyId;
                        facultyAllocations.SubjectId = model.SubjectId;
                        facultyAllocations.ClassId = model.ClassId;
                        facultyAllocations.Class_Start_Time = model.Class_Start_Time;
                        facultyAllocations.Class_End_Time = model.Class_End_Time;
                        facultyAllocations.IsActive = model.IsActive;


                        facultyAllocationservices.UpdateFacultyAllocationPresenter(facultyAllocations);
                        //return RedirectToAction("AsignClassFaculty");
                    }
                    else
                    {
                        facultyAllocations.FacultyId = model.FacultyId;
                        facultyAllocations.SubjectId = model.SubjectId;
                        facultyAllocations.ClassId = model.ClassId;
                        facultyAllocations.Class_Start_Time = model.Class_Start_Time;
                        facultyAllocations.Class_End_Time = model.Class_End_Time;
                        facultyAllocations.IsActive = model.IsActive;
                        facultyAllocations.CreatedDate = DateTime.Now;
                        facultyAllocationservices.SaveFacultyAllocation(facultyAllocations);

                       // return RedirectToAction("AllocationIndex");
                    }

                }
                ShowSuccessMessage("Success", "Faculty save successfully");
                return NewtonSoftJsonResult(new RequestOutcome<dynamic> { RedirectUrl = @Url.Action("AllocationIndex"), IsSuccess = true,Data="Data Save " });
            }
            catch (Exception ex)
            {
                //return NewtonSoftJsonResult(new RequestOutcome<dynamic> { RedirectUrl = @Url.Action("AllocationIndex", "FacultyAllocation") });
                return NewtonSoftJsonResult(new RequestOutcome<string> { Data = ex.GetBaseException().Message, IsSuccess = false });

            }

StudentApp.Web/Views/FacultyAllocation/AllocationIndex.cshtml
@{
    ViewBag.Title = "AllocationIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section styles{
    <link href="~/Content/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/Content/css/bootstrap-switch.css" rel="stylesheet" />
  
}

<section class="content-header">
    <h2>Faculty ClassAllocation Manager</h2>
</section>
<section class="content">
    <div class="row">
        @Html.Partial("_MessageNotification")
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="box">

                <div class="box-body">
                    <div class="clearfix">
                        <div class="btn-group">
                            <a id="AddEditFacultyAllocationModal" data-toggle="modal" href="@Url.Action("AddUpdateAllocation","FacultyAllocation")" data-target="#modal-add-edit-allocation" class="btn btn-primary">
                                <i class="fa fa-plus"></i> Assign Class
                            </a>
                        </div>


                    </div>
                </div>
                <div class="box-body table-responsive">

                    <table id="grid-allocation-management" class="table table-bordered table-striped table-condensed">
                        <thead>
                            <tr>
                                <th style="visibility:hidden">FacultyAllocation ID</th>
                                <th width="1%">#</th>
                                <th>Name</th>
                                <th>Class</th>
                                <th>Subject</th>
                                <th>Class Start Time</th>
                                <th>Class End Time</th>
                                <th>IsActive </th>
                                <th>Action </th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                        <tfoot></tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>



@Html.Partial("_modal", new Modal { ID = "modal-add-edit-allocation", AreaLabeledId = "modal-add-edit-allocation-label", Size = ModalSize.Large })
@Html.Partial("_modal", new Modal { ID = "modal-delete-allocation", AreaLabeledId = "modal-delete-allocation-label", Size = ModalSize.Medium })
@section scripts
{
    
    <script src="~/Scripts/views/FacultyAllocationList/AllocationList.js"></script>

}

StudentApp.Web/Views/FacultyAllocation/AsignClassFaculty.cshtml
@model SchoolApp.Web.Model.FacultyAllocationModel

@using SchoolApp.Web.Models


@section Styles{
    <link href="~/Content/css/bootstrap-switch.css" rel="stylesheet" />

    <link href="~/Content/timepicker/jquery.timepicker.min.css" rel="stylesheet" />

    }

<div id="adminUpdateLocationModal">

    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header ">
            <button type="button" class="close font16" data-dismiss="modal"><i class="fa fa-times"></i></button>
            Add Class Faculty
            <h4 class="modal-title"><b><span class="UpdateBrand"></span></b></h4>
        </div>
        <div class="modal-body">
           
                <div class="full-wdth clearfix otp-section">
                    @using (Html.BeginForm("SaveFacultyAllocation", "FacultyAllocation", null, FormMethod.Post, new { @class = "form-horizontal", id = "formAddEditAllocation" }))
                    {

                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true)


                        @Html.HiddenFor(model => model.FacultyAllocationId);
                        <div id="validation-summary"></div>
                        <div id="adminAddAllergyMessageDiv" class="alert " style="display:none"> </div>
                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.Label("Class", "Faculty Name", new { @class = "main-label requiredasterisk" })
                                @Html.DropDownListFor(x => x.FacultyId, Model.FacultyList, "Choose Faculty", new { @class = "form-control", id = "facultyListId" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.Label("Class", "Subject", new { @class = "main-label requiredasterisk" })
                                @Html.DropDownListFor(x => x.SubjectId, Model.SubjectList, "Choose Subject", new { @class = "form-control", id = "ClassListId" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.Label("Class", "Class", new { @class = "main-label requiredasterisk" })
                                @Html.DropDownListFor(x => x.ClassId, Model.ClassList, "Choose Class", new { @class = "form-control", id = "SubjectListId" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.Label("Class", "Class Start Time", new { @class = "main-label requiredasterisk" })
                                @*@Html.DropDownListFor(x => x.SelectedStartValue, Model.Values, "Choose Class Start Time", new { @class = "form-control", id = "starttime" })*@



                                @Html.TextBoxFor(x => x.Class_Start_Time, null, htmlAttributes: new { @type = "time", @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.Label("Class", "Class End Time", new { @class = "main-label requiredasterisk" })


                                @*@Html.DropDownListFor(x => x.SelectedEndValue, Model.period, "Choose Class End Time", new { @class = "form-control", id = "endtime" })*@
                                @Html.TextBoxFor(x => x.Class_End_Time, null, htmlAttributes: new { @id = "timefield ", @class = "form-control" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <div class="checkbox">
                                    @Html.CheckBoxFor(model => model.IsActive, new { @class = "form-checkbox" })
                                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="modal-footer customMargin">
                            <button data-dismiss="modal" id="btn-cancel" class="btn btn-default" type="button">Cancel</button>
                            <button class="btn btn-primary" id="btn-submit" type="submit">
                                Submit
                            </button>
                        </div>
                    }

                </div>
       
        
        
        </div>

    </div>
</div>
@*<script>
    

 
</script>
<script src="~/Content/timepicker/timepicker.js"></script>*@

StudentApp.Web/Views/FacultyAllocation/GetFacultyDasboard.cshtml
@model IEnumerable<SchoolApp.Web.Model.FacultyAllocationModel>

@{
    ViewBag.Title = "GetFacultyDasboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Model != null && Model.Any())
{
    <section class="content-header">
        <h1>Faculty Management</h1>
    </section>

    <section class="content">

        <div class="row">
            <div class="col-lg-3 col-6">

                <div class="small-box bg-primary">
                    <div class="inner">
                        <h3>55</h3>
                        <b>Faculty List</b>
                    </div>
                    <div class="icon">
                        <i class="ion ion-ios-book"></i>
                    </div>
                    <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>

            <div class="col-lg-3 col-6">

                <div class="small-box bg-yellow-gradient">
                    <div class="inner">
                        <h3>12<sup style="font-size: 20px">%</sup></h3>
                        <b>Class List</b>
                    </div>
                    <div class="icon">
                        <i class="ion ion-stats-bars"></i>
                    </div>
                    <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>

            <div class="col-lg-3 col-6">

                <div class="small-box bg-success">
                    <div class="inner">
                        <h3>22</h3>
                        <b>Subject List</b>
                    </div>
                    <div class="icon">
                        <i class="ion ion-pie-graph"></i>
                    </div>
                    <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>

            <div class="col-lg-3 col-6">

                <div class="small-box bg-olive">
                    <div class="inner">
                        <h3>165</h3>
                        <b>Student List</b>
                    </div>
                    <div class="icon">
                        <i class="ion ion-person-add"></i>
                    </div>
                    <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>

        </div>

        <div class="row">

            <div class="card">
                <div class="card-header">

                    <div class="row">
                        @{
                            var cuitem = Model.ToList().FirstOrDefault();
                            <div class="col-sm-12">

                                <div class="row bg-primary">
                                    
                                    <h3 style="text-align:center;"> <b>Name -</b>@cuitem.FacultyName</h3>

                                </div>
                                
                            </div>
                            <div class="col-sm-3">

                            </div>
                            <div class="col-sm-3"></div>

                        }

                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        @{
                            foreach (var item in Model)
                            {
                                <div class="col-sm-3">
                                    <h4><b>Subject Name</b>:@item.SubjectName</h4>
                                    <h4><b>Class Name</b>:@item.ClassName</h4>
                                    <h4><span><b>Start Time</b>:@item.Class_Start_Time</span> <span><b>EndTime</b>: @item.Class_End_Time</span></h4>
                                </div>
                            }


                        }


                    </div>
                </div>

            </div>
        </div>
    </section>

}
else
{
    <div class="row text-center">
        <h1>Record Not Found</h1>
    </div>

}
























































































@*@if (Model != null && Model.Any())
    {

        <div class="row">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        @{
                            var cuitem = Model.ToList().FirstOrDefault();
                            <div class="col-sm-3">
                                <h1>   <b>Name:</b>@cuitem.FacultyName</h1>
                            </div>
                            <div class="col-sm-3">

                            </div>
                            <div class="col-sm-3"></div>

                        }

                    </div>

                </div>
                <div class="card-body">
                    <div class="row">
                        @{
                            foreach (var item in Model)
                            {
                                <div class="col-sm-3">
                                    <h4><b>Subject Name</b>:@item.SubjectName</h4>
                                    <h5><b>Class Name</b>:@item.ClassName</h5>
                                    <h5><span><b>Start Time</b>:@item.Class_Start_Time</span> <span><b>EndTime</b>: @item.Class_End_Time</span></h5>
                                </div>
                            }


                        }


                    </div>
                </div>

            </div>
        </div>


    }
    else
    {
        <div class="row text-center">
            <h1>Record Not Found</h1>
        </div>
    }*@