StudentApp.Web/Controllers/ClassMasterController.cs
using SchoolApp.Data;
using SchoolApp.DataTable.Extension;
using SchoolApp.DataTable.Search;
using SchoolApp.DataTable.Sort;
using SchoolApp.Service.ClassMasterServices;
using SchoolApp.Web.Code.Serialization;
using SchoolApp.Web.Model;
using SchoolApp.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace SchoolApp.Web.Controllers
{
    public class ClassMasterController : BaseController
    {
        private readonly IClassMasterService _classmasterServices;
        public ClassMasterController(IClassMasterService classmasterServices)
        {
            this._classmasterServices = classmasterServices;

        }
        [HttpGet]
        public ActionResult ClassViewIndex()
        {
            return View();
        }


        [HttpPost]
        public ActionResult ClassViewIndex(SchoolApp.DataTable.DataTable dataTable)
        {
            List<DataTableRow> table = new List<DataTableRow>();

            List<int> column1 = new List<int>();
            for (int i = dataTable.iDisplayStart; i < dataTable.iDisplayStart + dataTable.iDisplayLength; i++)
            {
                column1.Add(i);
            }

            //This Methods for seraching in dataTable
            var query = new SearchQuery<ClassMaster>();

            if (!string.IsNullOrEmpty(dataTable.sSearch))
            {
                string sSearch = dataTable.sSearch.ToLower();
                query.AddFilter(q => q.Class.Contains(sSearch));
            }
            // This Methods for sorting in dataTable
            var sortColumnIndex = Convert.ToInt32(Request["iSortCol_0"]);
            var sortDirection = Request["sSortDir_0"];
            switch (sortColumnIndex)
            {
                case 2:
                    query.AddSortCriteria(new ExpressionSortCriteria<ClassMaster, string>(q => q.Class, sortDirection == "asc" ? SortDirection.Ascending : SortDirection.Descending));
                    break;

                //case 3:
                //    query.AddSortCriteria(new ExpressionSortCriteria<ClassMaster, bool>(q => q.IsActive, sortDirection == "asc" ? SortDirection.Ascending : SortDirection.Descending));
                //    break;
            }
            //for pagination
            query.Take = dataTable.iDisplayLength;
            query.Skip = dataTable.iDisplayStart;

            int count = dataTable.iDisplayStart + 1, total = 0;

            //To get data from table  using searchquery
            IEnumerable<ClassMaster> classMasters = _classmasterServices.GetClassMasterList(query, out total).Entities;

            foreach (ClassMaster classmaster in classMasters)
            {


                table.Add(new DataTableRow("rowId" + count.ToString(), "dtrowclass")
                {
                    classmaster.ClassId.ToString(), //0
                    count.ToString(),//1
                    classmaster.Class,//2
                    classmaster.IsActive?"Active":"Inactive" //3

                });
                count++;
            }
            return new DataTableResultExt(dataTable, table.Count(), total, table);
        }



        /// <summary>
        /// /Edit Code here 
        /// </summary>
        /// <returns></returns>



        //Edit Add
        public PartialViewResult AddUpdateClassMaster(int id=0)
        {

            ClassMasterViewmodel model = new ClassMasterViewmodel();
            ClassMaster classMaster = new ClassMaster();


            if (id > 0)
            {
                classMaster = _classmasterServices.FindById(id);
            }
            model.ClassId = id > 0 ? id : 0;
            model.Class = classMaster.Class;
            model.IsActive = classMaster.IsActive;


            return PartialView("AddUpdateClassMaster", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveClassMaster(int? id, ClassMasterViewmodel model)

        {

            try
            {
                if (ModelState.IsValid)
                {
                    ClassMaster classMaster = new ClassMaster();
                    if (model.ClassId > 0)
                    {
                        classMaster = _classmasterServices.FindById(model.ClassId);

                    }
                    else
                    {

                    }

                    classMaster.Class = model.Class?.Trim() ?? "";
                    classMaster.IsActive = model.IsActive;

                    _classmasterServices.SaveClassMaster(classMaster);





                }
                return RedirectToAction("ClassViewIndex");

            }
            catch (Exception ex)
            {

                return NewtonSoftJsonResult(new RequestOutcome<string> { Data = ex.GetBaseException().Message, IsSuccess = false });
            }

          
        }

      

        public PartialViewResult DeleteClassMaster()
        {
            return PartialView("_ModalDelete", new Modal
            {
                Size = ModalSize.Small,
                IsHeader = true,
                Message = "Are you sure want to delete this Class?",
                Header = new ModalHeader { Heading = "Delete Class" },
                Footer = new ModalFooter { SubmitButtonText = "Yes", CancelButtonText = "No" }
            });
        }

        [HttpPost]
        public ActionResult DeleteClassMaster(int id)
        {
            try
            {
                int get = _classmasterServices.DeleteClassMasterPresenter(id);
                if (get == id)
                {
                    ShowSuccessMessage("Success", "Class is successfully deleted", false);
                    return NewtonSoftJsonResult(new RequestOutcome<string> { Data = "Data Deleted" });
                }
                else
                {
                    return NewtonSoftJsonResult(new RequestOutcome<string> { Data = "Error Occourd" });
                }

            }
            catch (Exception ex)
            {
                return NewtonSoftJsonResult(new RequestOutcome<string> { Data = ex.GetBaseException().Message, IsSuccess = false });
            }

        }

    }
}

StudentApp.Web/Views/ClassMaster/AddUpdateClassMaster.cshtml
@model SchoolApp.Web.Model.ClassMasterViewmodel
@using SchoolApp.Web.Models


<div id="adminUpdateLocationModal">

    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header ">
            <button type="button" class="close font16" data-dismiss="modal"><i class="fa fa-times"></i></button>
            Add/Update  ClassMaster
            <h4 class="modal-title"><b><span class="UpdateBrand"></span></b></h4>
        </div>
        <div class="modal-body">
            <div class="full-wdth clearfix otp-section">
                @using (Html.BeginForm("SaveClassMaster", "ClassMaster", null, FormMethod.Post, new { @class = "form-horizontal", id = "formAddEditClassMaster" }))
                {

                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
                     

                    @Html.HiddenFor(model => model.ClassId);
                    <div id="validation-summary"></div>
                    <div id="adminAddAllergyMessageDiv" class="alert " style="display:none"> </div>
                    <div class="form-group">
                        <div class="col-sm-3 label-schedule">@Html.Label("Class", "Class Name", new { @class = "main-label requiredasterisk" })</div>
                        <div class="col-sm-10">
                            @Html.TextBoxFor(model => model.Class, null, htmlAttributes: new { @class = "form-control form-control-sm", placeholder = "Enter Class", maxlength = "100" })
                            @Html.ValidationMessageFor(model => model.Class, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="form-group">
                        @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="checkbox">
                                @Html.CheckBoxFor(model => model.IsActive, new { @class = "form-checkbox" })
                                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="modal-footer customMargin">
                        <button data-dismiss="modal" id="btn-cancel" class="btn btn-default" type="button">Cancel</button>
                        <button class="btn btn-primary" id="btn-submit" type="submit">
                            Submit
                        </button>
                    </div>
                }

            </div>
        </div>

    </div>

</div>
<link href="~/Content/css/bootstrap-switch.css" rel="stylesheet" />

StudentApp.Web/Views/ClassMaster/ClassViewIndex.cshtml
@using SchoolApp.Web.Models
@using SchoolApp.Web.Code.Serialization
@{
    ViewBag.Title = "ClassViewIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section styles{
    <link href="~/Content/css/dataTables.bootstrap4.min.css" rel="stylesheet" />

}

<section class="content-header">
    <h1>
        Manage Class Master
    </h1>

</section>
<section class="content">

    <div class="row">
        <div class="col-xs-12">
            <div class="box">

                <div class="box-body">
                    <div class="clearfix">
                        <div class="btn-group">
                            <a id="addClassMastermentmodal" data-toggle="modal" href="@Url.Action("AddUpdateClassMaster","ClassMaster")" data-target="#modal-add-edit-classmaster" class="btn btn-primary">
                                <i class="fa fa-plus"></i> Add New
                            </a>
                        </div>
                    </div>
                </div>
                <div class="box-body table-responsive">

                    <table id="grid-classmaster-management" class="table table-bordered table-striped table-condensed">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th width="2%">#</th>
                                <th>Class</th>
                                <th>IsActive</th>
                                <th>Action</th>

                            </tr>
                        </thead>
                        <tbody></tbody>
                        <tfoot></tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

@Html.Partial("_Modal", new Modal { ID = "modal-add-edit-classmaster", AreaLabeledId = "modal-add-edit-classmaster-label", Size = ModalSize.Large })
@Html.Partial("_Modal", new Modal { ID = "modal-delete-classmaster", AreaLabeledId = "modal-delete-classmaster-label", Size = ModalSize.Large })
@section scripts
{
    <script src="~/Scripts/views/classmaster/classmaster.js"></script>
    <link href="~/Content/css/bootstrap-switch.css" rel="stylesheet" />
}